from .zhangyu_gpt_img2 import NODE_CLASS_MAPPINGS as GPT_NODE_CLASS_MAPPINGS
from .zhangyu_gpt_img2 import NODE_DISPLAY_NAME_MAPPINGS as GPT_NODE_DISPLAY_NAME_MAPPINGS
from .zhangyuapi_prompt_control_nodes import NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS
from .zhangyuapi_prompt_control_nodes import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS
from .zhangyu_img import NODE_CLASS_MAPPINGS as NEWAPI_NODE_CLASS_MAPPINGS
from .zhangyu_img import NODE_DISPLAY_NAME_MAPPINGS as NEWAPI_NODE_DISPLAY_NAME_MAPPINGS
from .video_node import NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS
from .video_node import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS


NODE_CLASS_MAPPINGS = {
    **GPT_NODE_CLASS_MAPPINGS,
    **PROMPT_NODE_CLASS_MAPPINGS,
    **NEWAPI_NODE_CLASS_MAPPINGS,
    **VIDEO_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GPT_NODE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
    **NEWAPI_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
}


WEB_DIRECTORY = "./web"


__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
