from .gpt_2_0_node import NODE_CLASS_MAPPINGS as GPT_NODE_CLASS_MAPPINGS
from .gpt_2_0_node import NODE_DISPLAY_NAME_MAPPINGS as GPT_NODE_DISPLAY_NAME_MAPPINGS
from .luck_prompt_control_nodes import NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS
from .luck_prompt_control_nodes import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS


NODE_CLASS_MAPPINGS = {
    **GPT_NODE_CLASS_MAPPINGS,
    **PROMPT_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GPT_NODE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
}


WEB_DIRECTORY = "./web"


__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
